:PROPERTIES:
:ID:       1764cef0-a257-4ad9-9339-099f23e1dc72
:END:
#+title: Lakehouse Stories
#+STARTUP: overview
#+STARTUP: logdone

* Characters

** Tito the Tick
:PROPERTIES:
:ID:       7b32af1a-32d2-4df1-8700-d274465277f7
:END:
** Wally the Wolf
:PROPERTIES:
:ID:       422122d2-07d0-49fa-b106-702075a1c6bd
:END:
** Bernie the Badger
:PROPERTIES:
:ID:       268f6544-b4b9-4dfa-bd6e-00d694dfc166
:END:
** Hito the Horse
:PROPERTIES:
:ID:       8e7bfac9-31b5-4d05-af55-84b9435286b5
:END:
** Patty the Panther
:PROPERTIES:
:ID:       58f42094-159f-407a-8375-0a92e6773376
:END:
** Rachel the Rabbit
:PROPERTIES:
:ID:       a886d0ce-88f4-4c3f-a17e-bc9b5e76ee0c
:END:
** Rebecca the Racoon
:PROPERTIES:
:ID:       d5a25053-fc1a-4fbb-a2a2-51be2d3aac29
:END:
** Seymore the Snake
:PROPERTIES:
:ID:       9b5fe818-c5c0-4d13-acad-7980b9ee3364
:END:
** Felix the Fox
:PROPERTIES:
:ID:       b6adb33b-b9c2-4caa-96ea-f36ee1eb5edc
:END:

Father of [[id:42920b47-3149-4cb5-81f6-81ff5ae3da13][Fiona the Fox]]
Son of [[id:d0af1f4b-cc8e-4de2-91ab-bf809d73f66f][Frido the Fox]]
** Frido the Fox
:PROPERTIES:
:ID:       85146841-2c20-4966-b98c-2f13cfe0dafa
:END:
** Fiona the Fox
:PROPERTIES:
:ID:       781795cd-c683-4f2a-8d65-16494b76ccd3
:END:
** Dolly the Deer
:PROPERTIES:
:ID:       1ef72157-3b08-4e2c-8524-6c045d25b577
:END:
** Mr. Finnigan
:PROPERTIES:
:ID:       ce7b3172-63d0-4762-ba57-9e046ded07a4
:END:
** Bennie the Bear
:PROPERTIES:
:ID:       c73b3bde-935f-4c39-bf94-ef67343b159a
:END:
** Penny the Porcupine
:PROPERTIES:
:ID:       721af946-504b-4aaf-b2f5-d4bf7e2960a8
:END:
** Charlie the Chicken
:PROPERTIES:
:ID:       14feba66-8711-4ba2-9f4a-bd8e082eca1d
:END:
** Marigold the Moose

* Tito the tick
:PROPERTIES:
:ID:       be368967-2a04-494d-b2e2-0931ca1bf950
:END:
[[id:7b32af1a-32d2-4df1-8700-d274465277f7][Tito the Tick]] lives in the woods around the lakehouse.
He sees something golden-brown and climbs onto it.
He continues climbing, toward a bright light.
Tito feels two fingers grabbing him, and pulling.  And he can't hold on.
Then Tito feels a flushing, and he goes down the drain! He's in a toilet!
Tito spends a few weeks inside the plumbing of the lakehouse, slowly making his way through the septic system, until finally he's released beneath the front yard.
It's been many weeks, but he finally makes it back to the tree branch where he first saw the golden-brown thing.
There he tells his friends and family about his adventure.
The next day while he is sitting on a his tree branch, he sees something curly and brown...
/story continues with similar tale of getting flushed down the toilet/

* Wally the wolf eats the chickens
:PROPERTIES:
:ID:       9196f938-85a4-47fa-87bd-a35307648f32
:END:
Once upon a time  me there was a wolf named Wally.
Everyone likes Wally, but he is not perfect. He likes to eat the Finnigans' chickens.  Wally tries to pretend that it isn't him, and blames it on the his nemisis, Frido the Fox.
One day the Finnigans discover that their chickens have been eaten, and they blame Wally.  They call the police.
The police tell Wally, "we'll give you one more chance, becuase we're bros".
Wally decides that he will make sure the Finnigans cannot prove that he ate the chickens, and will ensure that Frito gets in trouble for it instead.
Wally tells the Finnigans that there is a bear swimming in the lake.
But it turns out, there really is! Bennie the bear is swimming in the lake.
The Finnigans head to the lake to check out this amazing sight.
While they are gone, Wally eats the chickens.
The Finnigans come back from the lake, and see that their chickens are gone.
Wally tells the Finnigans that Frito the Fox did it
And the Finnnigans actually believe him a little bit, because Wally is a charming and persuasive guy


* Wally the wolf runs for mayor
:PROPERTIES:
:ID:       f17202d4-dd34-4293-8a23-e678f7c03645
:END:
There is going to be an election in the town where the lakehouse is!
The town needs a new mayor.  Everyone is very excited and talking about the election.  Wally the wolf and Mr. Finnigan are going to run for mayor.
Mr. Finnigan and is responsible and well-respected member of the community. He would make a great mayor.
Wally is an untrustworthy and dishonest predator. Everyone knows that Wally should not be the mayor. But, he's is /very/ well liked and very clever.
Wally decides to cheat.
Wally goes to Mr. Finnigan's backyard, where they keep the chickens.  He tells the chickens his plan.
The chickens are terrified of Wally.  He has eaten many of the their friends and family, and they know he'll eat them to.  So they listen to what he has to say.
Wally tells the chickens his idea.  They will all go to vote at the upcoming election.  Since no one can tell them apart, they will continue to vote at the upcoming election, as many times as they can. And of course, they will cast these votes for Wally.  Or else!
The chickens do as they are told.  On election day, the voter turnout for the mayoral election is huge! (most of the votes are by chickens).  Wally wins by a slim margin.
Wally is the new mayor! Mr. Finnigan is suspicious, because it's obvious that eveyone knows that he would make an excellent mayor. Wally is focused on his first grift.


* Hito the horse and his long mane
:PROPERTIES:
:ID:       5919a7ba-caad-4785-8868-14f1d7f51444
:END:
There was a horse Hito who lived in the woods near the lakehouse.
The lady of the woods kidnapped Hito, when she was just a young philly.
The lady of the woods Hito in her cabin, and /never/ let her out.
Wally the wolf has heard the tale of the lost horse. He decides to try to find Hito after all these years.
Wally teams up with Frito and Felix the foxes. They used to be bitter enemies, but they've started to work together recently on various scams and chicken-eating adventures
One day Wally is exploriing around the Lady of the Woods cabin, and here's a horse's neigh. It sounds beautiful.  He investigates further, and discovers Hito the missing horse!  Hito has an incredible long mane that connects to her tail.
Wally helps Hito escape from the Lady of the Woods cabin.
They are running away from the lakehouse, and wind up at a pizza shop in the town of Port Jervis.  Hito is a little bit afraid of the townsfolk, but it turns out they are all very nice to her.  And teach her how to throw pizza dough in the air.
A couple of police officers in the pizza shop warn Wally that Frito and Felix tipped off the FBI.  The feds are close by, and will be coming into the pizza shop any minute!
Wally grabs Hito and they make a run for it, staying off of the main roads, and following the river back to the lakehouse.
It's so dark.  They get trapped in various compromising situations, but Hito's glowing mane helps them get out.
One of the FBI's dogs find Wally and Hito.  But Wally cuts a deal with him.  Wally will go to jail at the end of the day, after Hito is safe.
Wally and Hito see a mural of the lost horse. The see a lantern festival, and ride a canoe in the lake. Hito finds the lady of the woods.  She brings him back to the cabin.
Hito sees Wally being draffed of to jail by the feds.  It looks like he's sailing away!
Hito realizes that she is the lost horse from the mural.
She runs away towards the lake.
/this story ends with the lady of the woods holding onto Hito's mane, and the mane gets cut/

* The panther's new suit
:PROPERTIES:
:ID:       9fd5719b-3786-40a9-ac9f-cd69951ac9a9
:END:
** Act 1
[[id:58f42094-159f-407a-8375-0a92e6773376][Patty the Panther]] lived in the woods near the lakehouse. Patty cared very much about how he looked.  He was always making sure that his fur was clean and beautiful and his teeth were pearly white.
The other animals thought that Patty was kinda silly, but they played along because they were afraid of him.  He was ultimately a vicious and ruthless predator, living at the top of the local foodchain.
Rebecca the Raccoon and Seymore the Snake were two local ne'er-do-wells who were always looking for the next trick deal. They observed that Patty's vanity made him vulnerable.
One day, Rebecca and Seymore approached Patty by the lake, as Patty was combing his fur and admiring his reflection.  They told Patty about a tailor, just accross the river in Pennsylvania, who manufactured /amazing/ animal clothes.  Specifically, a beautiful coat that would fit a four-legged creature like Patty perfectly.
But that's not all.  These coats had an amazing special property.  Only those who were good enough, could see them.  Anyone who was not worthy, wouldn't notice the coat at all.
Patty wanted nothing more than to be good enough, and better than others.  He wanted this beautiful coat, he wanted to be sure that he was good enough to see it, and he wanted to know exactly who was not worthy.  He had to have this coat!
Patty asked Rebecca and Seymore if they could help him get one of these amazing coats?
Rebecca and Seymore were happy to agree. They made sure that Patty paid them in full, up front.
Rebecca and Seymore then spent the weekend rafting, camping, and eating hot dogs in the Delaware River Gap.
** Act II
When the next week rolled around, they found Patty again, cleaning his paws with some left over mouse bones.  They approached Patty solemly, Rebecca with her arms outstretched, as if she were holding a heavy robe.  They looked at Patty expectedly.
Patty immediatley squilled with excitement.  With great flourish, Patty made a show of putting on the invisible vestments.  Patty turned around with pride, showing Rebecca and Seymore his most flattering angles.  The Raccoon and the snake smiled, and gushed, complimenting Patty on his new clothes. None of the three even bothered to mention that they could see the clothes.  Of course they could, they were all surely worthy.
** Act III
Patty could hardly wait to show all of the other animals his beautiful new clothes.  He imagined the way he would belittle anyone who could not see them. Patty could hardly sleep that night.
The next morning Patty arose out of his den before sunrise, put on his new clothes, and went out into forest looking for animals to impress.
He saw many that morning.  Each time he came upon someone he would say "Don't you like me new coat? Isn't it beautiful?" And each time the animal would stare, confused, but ultimately decide to play along. "Ya, sure Patty.  Looking good bro".  Again, Patty was a viscious and ruthless predator, and none of the animals wanted to upset him.
A little bit after lunch, Patty strolled by the foresthood school. All of the school-age animals were sitting in a circle near the spillway, listening to [[id:a886d0ce-88f4-4c3f-a17e-bc9b5e76ee0c][Rachel the Rabbit]] conduct a lesson about forest fires.  Patty particularly liked Rachel the Rabbit.  Everyone was quite fond of Rachel the Rabbit.

"Sup Rachel, what do you folks think of my amazing, new coat?" Patty said, turning around.  After a pause, Rachel started to mumble something, but then [[id:781795cd-c683-4f2a-8d65-16494b76ccd3][Fiona the Fox]] spoke up.

"You're wearing nothing dude! You haven't got on any coat.  What's wrong with you Patty.  Get a grip", Fiona said dismissively. Then she turned her attention back to the lesson.

[[id:1ef72157-3b08-4e2c-8524-6c045d25b577][Dolly the Dear]] let a muffled laugh escape. Then [[id:721af946-504b-4aaf-b2f5-d4bf7e2960a8][Penny the Porcupine]] giggled.  Then it was a cascade of laughter.  All of the children joined in to laugh at Patty.  Even Rachel snickered. Other animals in the forest heard the commotion and joined in.  Soon the entire forest had heard, and they all laughed at Patty.

Patty was furious.  He snarled his teeth, arched his back, and ran off.  He found Rebecca the Raccoon and Seymore the Snake lounging near the other side of the lake.  He tour their bodies to shreds and ate them.

* Bennie the bear swims in the lake
:PROPERTIES:
:ID:       5d2d9981-e899-4caf-8034-5bd9cd3dc7a5
:END:
[[id:c73b3bde-935f-4c39-bf94-ef67343b159a][Bennie the Bear]] loved to eat trash. If he ever found a piece of trash while meandering through the forest, he would return there again and again looking for more. He often visting people's yards, and stole their garbage. One day he heard a story about a treasure of garbage at the bottom of the lake. Bennie was very excited! He though he could try swim down to the bottom of the lake to find the garbage. So he tried. Down at the bottom of the lake, he found a pile of old nasty moldy trash, and he sunk his teeth in. But most of it disintergrated into silt.  There were only six real pieces of garbage to speak of. Bennie knew this couldn't be the real treasure that he heard about.  So he kept searching.  He found three more pieces of trash at the bottom of the lake, arranged in a single file line.  He kept searching for the rest of the day, but didn't have much luck.  Just a little bit of trash, here and there.

When he was done, he went straight to find his bear friends.  He told them, "you were wrong, dude!"

* Frido the fox (and his son Felix) saved from drowning by Bennie the bear
:PROPERTIES:
:ID:       b53bdf6a-3e57-43f6-8926-dc8cc9b0ea70
:END:
[[id:422122d2-07d0-49fa-b106-702075a1c6bd][Wally the Wolf]] was walking through the woods one day.  He saw [[id:ce7b3172-63d0-4762-ba57-9e046ded07a4][Mr. Finnigan]] setting a trap for [[id:85146841-2c20-4966-b98c-2f13cfe0dafa][Frido the Fox]]. Wally was concerned. Wally needs Frido to be free, so that Wally can blame Frido for stealing Mr. Finnigan's chickens.  Then Wally thought of Frido's son, [[id:b6adb33b-b9c2-4caa-96ea-f36ee1eb5edc][Felix the Fox]]. But still, it would be great if there were two foxes around to blame, instead of one.  If there were only one around, then maybe folks would start to wonder whether /Wally/ was working with the other fox to steal the chickens.  That would not be good! Maybe Wally could blame chicken stealing on [[id:781795cd-c683-4f2a-8d65-16494b76ccd3][Fiona the Fox]]. Might be a tough sell, since she's only 10 years old.

The trap sprung while Frido was walking by. He jumped to the side to avoid the trap, and didn't get caught.  But he stumbled and fell into the lake.

Wally saw the whole thing.  He also saw that [[id:c73b3bde-935f-4c39-bf94-ef67343b159a][Bennie the Bear]] was swimming in the lake, further in towards the deeper end. Wally is used to seeing this.  Bennie loves swimming.

Wally retuns his attention to Fiona.  He thinks that maybe he can convince everyone that she's old enough to be a thief. Maybe he can try to take a photograph of Fiona eating chicken on thanksgiving, and use that to frame her.  Or maybe he should put on a fox costume, and pretend to be Fiona stealing a chicken. Or maybe he can manipulate Fiona into actually stealing a chicken, and Wally can make sure that she get's caught.

Later that week, Wally steels one of Mr. Finnigan's chickens.  This time he makes sure that Felix gets the blame. It was only one chicken, and everyone assumes that Felix stole the chicken without a partner.

Later that month, Mr. Finnigan is at it again, setting up another trap for Felix. This time, Wally tries to warn Felix, but Felix doesn't listen, and the trap springs.  Just like last time, Felix avoids the trap, but winds up on the lake again!

The next day, Mr. Finnigan finds that /many/ of his chickens are gone.  This time Wally is surpised as well, because he didn't do it! Snooping around, Wally finds a trail of chicken feathers leading through the woods.  He follows the trail, leading to Bennie's den.  Wally is confused. Bennie doesn't like to eat chickens.  He eats garbage.

Wally peaks his head into Bennie's den.  There is Felix and Frido, sitting comfortably inside Bennie's den, sucking on chicken bones.

Wally runs away, looking for Fiona. He finds her near the foxes' den. "Fiona," he says, "you're going to love this."

He leads Fiona back to Bennie's den. "Where are you taking me," Fiona asks along the way.

When they get there, Fiona peaks into Bennie's den and cries, "Dad, Grandpa!"

Then Wally asks, "why are you two here?"

Bennie says, "I saved them when they were drowning".

Wally says, "well its not nice to hide like that.  You should tell everyone that you're alive"

* Dolly the deer goes to school with Fiona the fox and there's a fire. Everyone helps
:PROPERTIES:
:ID:       948c9810-1d1b-4ddc-92fb-eef3b20a4ba8
:END:
Dolly and Fiona are in the same class in the foresthood school. Its a small school, so each class has three different ages. Dolly is 8. Fiona is 10.  There are some nine year old animals in the class too.

One summer morning, [[id:721af946-504b-4aaf-b2f5-d4bf7e2960a8][Penny the Porcupine]] meets Dolly and Fiona on the way to school. Together, they walk to [[id:a886d0ce-88f4-4c3f-a17e-bc9b5e76ee0c][Rachel the Rabbit]]'s classroom.  This morning the class is being held in the ampitheater.

"Hello Ms. Rachel," says Penny.

"Today we are going to have a lesson about predators."

"I'm a predator," says Fiona.

Outside the school, Wally is walking around.  He sees two twigs outside the ampitheater. Suddenly, the twigs snaps and a small fire starts. The fire quickly spreads.

"I better warn Rachel and the other teachers," Wally thinks to himself.

Just then, the fire spreads and blocks his path.  He can't get through!

Rachel is the first to smell the fire.  She goes to investigate further, then quickly turns around and hops back to the class.  "Attention everyone! Forest Fire! This is not a drill! Quickly, head towards the lake.  Collect as much water as you can."

"And remember, do not drink the water."

Dolly asks, "What about the younger kids?  They are going to be so scared."

"Well if we collect a lot of water and put out the fire, they'll be ok"

Penny says, "remember what you taught us in our forest fire safety course?  We should make a fireman's brigade to bring the water to the fire."

"Oh you are right Penny!  I'm so glad you listened in class."

Fiona says, "if anyone gets scared during the fireman's brigade, just pretent you are playing hot potato :)"

The fireman's brigade works! The kids are able to put out the fire.  Mostly by pretending to play hot potato.  Wally escapes unharmed.

* Dolly the deer plays hide and seek
:PROPERTIES:
:ID:       759766b0-6c72-4196-b894-34f9ddd6b612
:END:

Dolly the Deer was scared of everyone, other than her friends [[id:721af946-504b-4aaf-b2f5-d4bf7e2960a8][Penny the Porcupine]], [[id:781795cd-c683-4f2a-8d65-16494b76ccd3][Fiona the Fox]], and her parents. Whenever she saw [[id:ce7b3172-63d0-4762-ba57-9e046ded07a4][Mr. Finnigan]], she would run away and hide behind a tree. Some of the boys at school would tease her, and say she was playing hide and seek. Dolly was actually really good at hide and seek for this reason!

Once day, Fiona asked to play hide and seek with Dolly. "Sure", said Dolly.

Fiona said, "can you be the seeker this time?" "Ok", said Dolly.

Fiona went off to hide, while Dolly closed her eyes and counted to 20.

Since Dolly spent so much time hiding, she knew all the good hiding spots, and was a pretty good seeker.

But very shortly after Dolly started looking for Fiona, Dolly saw Mr. Finnigan walking through the woods.  Dolly quickly ran off to hide.  She went to her best, super secret, impossibl to find hiding spot.

There was Fiona!

"You found me", Fiona said.

Fiona didn't know that Dolly had just been trying to hide from Mr. Finnigan herself.

Dolly said, "I guess it's time for us to go to school."  So Dolly and Fiona went to school together.

* Frido the fox steals the chickens
:PROPERTIES:
:ID:       d3c88772-d690-4cb7-b023-69d73f9b5ba5
:END:

** Act I
Frido the Fox loved to steal chickens. Sometimes when he was about to steal a chicken, he would come across [[id:422122d2-07d0-49fa-b106-702075a1c6bd][Wally the Wolf]] .  Wally was also obsessed with [[id:ce7b3172-63d0-4762-ba57-9e046ded07a4][Mr. Finnigan]]'s chickens.  Both Frido and Wally like to steal and eat the chickens.

One day Frido had a plan.  He knocked on Mr. Finnigan's door, and when Mr. Finnigan answered Frido said, "Hello Mr. Finnigan.  I just saw [[id:c73b3bde-935f-4c39-bf94-ef67343b159a][Bennie the Bear]] swimming in the lake."

Mr. Finnigan was shocked.  A bear, swimming in the lake? He /had/ to see this.  He called for his wife, Mrs. Finnigan, and the two went off running towards the lake.

While the Finnigans were away, Frido went directly to the chicken coop.

"Hello chickens", he said.

"Hi, I'm [[id:14feba66-8711-4ba2-9f4a-bd8e082eca1d][Charlie the Chicken]]", squeeked a voice from inside the chicken coop.

"He's Charlie the Upside Down Chicken," called another voice.  "Look at him, he's standing on his head!"

Indeed, Charlie the Chicken was standing on his head while he spoke to Frido.

Then another voice squeeked from the chicken coop.  "You're not Charlie the Chicken, I'm Charlie the Chicken".

"Neither of you are Charlie the Chicken," said another voice. "/I'm/ Charlie the Chicken".

"Whoa.  There are a lot of you named Charlie.  Do any of you have any other names?"

"I'm Cherrie"
"I'm Chariot"
"I'm Charlotte"
"I'm Chuck"
"I'm Charles"
"I'm Cherrie too"
"They call me Chuck"
"I'm another Charlie"
"My name is Charles"

And so on on.  This went on for some time.

Finally Frido cut them off. "You know chickens, I heard about a bike store down in Port Jervis."

"Let's go", shouted about 25 chickens.

The rest said, "We'll come only if Charlie stops standing on his head."

"Fine, I guess I'll be Charlie the regular-standing-on-his-feet chicken"

Frido opened the door of the chicken coop, and the chickens rushed out like a herd of stampeding wildebeasts. The bumped into each, trampled over each other, feathers flying every which way. It seemed to Frido that nearly a thousand chickens had just come running out of the chicken coop.

"It was so /squished/ in there", shouted one of the last chickens to come out of the coop.  "I could barely hear myself think in there, with all those chickens squeeking.  I bet you didn't even hear me say my name".

"What's your name", asked Frido.

"Charlie"

Frido shook his head, and led the chickens off to the bike store.

** Act II
Two hours later, Wally saw Frido walking down the road.  Behind Frido squalked a herd of about a thousand ckickens, many of them riding tiny bicycles.  One of them was riding a bicyle upside down.  He was walking on is feet, holding the bicycle upside down above his head!

"All right you Charlies, go ahead and hide your bicylces in your boxes in the chicken coop.  Mr. Finnigan can't find out about this".

Wally was gobsmacked.  Frido had managed to extract the chickens from the chicken coop, but had spent the afternoon outfitting them with bicycles, instead of eating them!

Wally knew that more than half of these creatures were named Charlie, god knows why. He also knew that the silly fella holding the bicycle over his head was a Charlie.

* The funeral of Felix the fox
:PROPERTIES:
:ID:       a4edc4f9-2063-40d1-9a45-0af481719b96
:END:

[[id:781795cd-c683-4f2a-8d65-16494b76ccd3][Fiona the Fox]] was asleep in her den. She heard her mother call out, "get up Fiona, it's time for breakfast."

Fiona ate some breakfast, then ran off to the stream.  She swam around until her fur was a deep black color. After that she dried herself off, but made sure her fur retained as much black color as possible. Then Fiona and her mother made their way to the spillway.  Her mother's fur was also a dark color this morning.

They collected a log, and fashioned it with their claws into the shape of Felix's body.  Then they put it in a wooden box they had stolen from a cabin in the woods.  Some other foxes arrived, and together they dug out an empty den near the Fox family's home.

One of the foxes who had come to pay his respects, had brought with him a chicken, recently stolen from [[id:ce7b3172-63d0-4762-ba57-9e046ded07a4][Mr. Finnigan]]'s chicken coop.  The funeral attendees passed around the chicken, each taking a small piece, and then they put the rest inside the box.

"Hmmm, that's good Charlie", someone remarked.

The burial was finished around 2:30 in the afternoon.

Fiona and her mother went back home. Friends from the forest came and went throughout the day, offering condolensces and memories of [[id:b6adb33b-b9c2-4caa-96ea-f36ee1eb5edc][Felix the Fox]].  They ate, and shared stories, and remembered Felix.

Later that day, Fiona was still thinking about the chicken they had shared at the funeral.  She wished Felix was still alive, she so /loved/ the chicken that Felix would bring home every week.

Fiona remembered how everytime Felix brought home a chicken, she would ask, "is this one's name Charlie?"  And Felix would inevitably say, "no, not this time.  We got ourselves here a Charles."  She smiled, cherishing the memory.

Before dinner time, the mourners made their way over to the woodstack.  They took turns carving depictions of Felix into the wood. Fiona's carving was very impressive.  She had taken an art class that year at school. Her carving was of a scene of Felix on top of Mr. Finnigan's chicken coop, trying to claw his way in.


* Bernie the Badger
:PROPERTIES:
:ID:       da62e3e4-f5d3-427c-8d8e-46461817c4cf
:END:


* Marigold the Moose and her yellow touch

** Act I
Marigold the Moose had a special talent.  Anything she touched became a yellowish gold color. Whenever she ate something, her mouth would turn it yellow, so she always was eating yellow food.  One day she saw an an amazing looking ampitheater, with many different colors.  There was a fox in the ampitheater.  The fox was staring straight at Marigold.

"Hi, I am Fiooooona the fooooox", said Fiona the fox, in a silly, ghostly way.  "I knoooooow you have a magic touch to make things yellloooooooow, but I knooooooow that the wooooorld cannot be completely yelloooooooow".  I will give you threeeee tests, and if you doooooon't pass all three teeeeests, then I'll take away your magic toooooooooouch.

"What three tests?" asked Marigold in a normal voice.

"You will soon seeeeeeee," said Fiona.

** ACT II
One morning, Marigold heard a strange voice in her head. "Yooooou're first task is to not tuuuuuurn anything yellooooooow for 3 minuuuuuuuutes, staring nooooooooooow"

But Marigold didn't last for even 50 seconds.  She couldn't help touching stuff, and all that stuff became yellow.

She heard another voice in her head. "Yoooooou have faaaaailed my fiiiiiirst teeeeeest!"  "My seeeeeeecond teeeeest is even haaaaarder"

"Yoooooouuu must not maaaake anything yelloooooow for teeeeeeen minuuuuuuutes"

But Marigold failed the test again.  She didn't last even two seconds befoe touching something, and making it yellow.

She heard another voice. "Yooo have faaaaaailed my seeeeeecond teeeeeeest" "My thiiiiiiird teeeeeeest is the haaaaaardest yet!"

"You must make noooooothing yeeeeeellow for one whoooooole hoooooooooour!"

This time, Marigold was able to last 10 minutes.  "Improoooooooovement".

"Now I muuuuuust take away your pooooooower to make stuff yelllooooooooow"

** ACT III
Suddenly, Marigod the Mooose felt different.  She felt like she didn't have the power to make stuff yellow anymore.  She decided to test it out.  She reached out and touched the bark of a nearby oak tree.  Nothing happpened.  She touched the canoes down by the lake.  Nothing.  She ran over to the elephant graveyard and touch every single rock peaking out of the water.  Nothing happened at all.

Soon, Marigold picked up a new hobby.  Walking up and down the stairs, over and over again.


* ~NOTE~ No school in the winter, because the some of the animals are hybernating
